language: python
python:
  - 2.7
  - 3.6
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace
# command to run tests
script: nosetests --with-doctest
